$background = 130d0b
$onBackground = f9e0da
$surface = 130d0b
$surfaceDim = 130d0b
$surfaceBright = 372925
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a110f
$surfaceContainer = 221714
$surfaceContainerHigh = 291d1a
$surfaceContainerHighest = 30231f
$onSurface = f9e0da
$surfaceVariant = 30231f
$onSurfaceVariant = bca6a1
$outline = 84716c
$outlineVariant = 554440
$inverseSurface = fff8f6
$inverseOnSurface = 5d5350
$shadow = 000000
$scrim = 000000
$surfaceTint = f9b7a5
$primary = f9b7a5
$primaryDim = eaa998
$onPrimary = 613428
$primaryContainer = 764638
$onPrimaryContainer = ffdbd2
$inversePrimary = 855244
$primaryFixed = ffbcab
$primaryFixedDim = f0af9d
$onPrimaryFixed = 4e2519
$onPrimaryFixedVariant = 704033
$secondary = e7bdb2
$secondaryDim = d8b0a5
$onSecondary = 563931
$secondaryContainer = 51342d
$onSecondaryContainer = dfb6ab
$secondaryFixed = ffdbd1
$secondaryFixedDim = f6cbc0
$onSecondaryFixed = 553831
$onSecondaryFixedVariant = 74544b
$tertiary = ffe1b1
$tertiaryDim = f8d291
$onTertiary = 694f1b
$tertiaryContainer = f8d291
$onTertiaryContainer = 604713
$tertiaryFixed = f8d291
$tertiaryFixedDim = e9c484
$onTertiaryFixed = 4b3401
$onTertiaryFixedVariant = 6a501c
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = a0695a
$secondaryPaletteKeyColor = 926f66
$tertiaryPaletteKeyColor = 90723b
$neutralPaletteKeyColor = 807471
$neutralVariantPaletteKeyColor = 86736e
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = a0695a
$secondary_paletteKeyColor = 926f66
$tertiary_paletteKeyColor = 90723b
$neutral_paletteKeyColor = 807471
$neutral_variant_paletteKeyColor = 86736e
$term0 = 353433
$term1 = ff572d
$term2 = ffbd98
$term3 = ffdfd3
$term4 = b9ab66
$term5 = f29083
$term6 = ffbb87
$term7 = efd2c7
$term8 = b49e96
$term9 = ff8768
$term10 = ffd5be
$term11 = fff1ec
$term12 = dcbc93
$term13 = ffa99b
$term14 = ffd2b4
$term15 = ffffff
$rosewater = ffeeea
$flamingo = ffd9d2
$pink = ffd3cf
$mauve = ffa9ab
$red = ff9888
$maroon = faab9c
$peach = ffbfaa
$yellow = ffeee7
$green = ffd8be
$teal = ffdb94
$sky = e1df87
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbbc2
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5c5e
$kvisitedSelection = cf5c5f
$knegative = ea5638
$knegativeSelection = ea5639
$kneutral = ff8a62
$kneutralSelection = ff8a63
$kpositive = fa8e1e
$kpositiveSelection = fa8e20
$text = f9e0da
$subtext1 = bca6a1
$subtext0 = 84716c
$overlay2 = 74635e
$overlay1 = 635450
$overlay0 = 534642
$surface2 = 443835
$surface1 = 342b28
$surface0 = 241c19
$base = 130d0b
$mantle = 130d0b
$crust = 120c0a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
