local function make_combo(str)
    local res = str:gsub(",%s*", " + "):gsub("^%s*%+%s*", ""):gsub("%s*%+%s*$", "")
    res = res:gsub("Super", "SUPER"):gsub("Ctrl", "CTRL"):gsub("Alt", "ALT"):gsub("Shift", "SHIFT")
    return res
end
-- Submap reset omitted as it is unsupported in hl.config
hl.bind(make_combo("Super + Ctrl, Return"), hl.dsp.global("caelestia:launcher"))
hl.bind(make_combo((_G["kbSession"] or "")), hl.dsp.global("caelestia:session"))
hl.bind(make_combo((_G["kbClearNotifs"] or "")), hl.dsp.global("caelestia:clearNotifs"), {locked = true})
hl.bind(make_combo((_G["kbShowPanels"] or "")), hl.dsp.global("caelestia:showall"))
hl.bind(make_combo((_G["kbLock"] or "")), hl.dsp.global("caelestia:lock"))
hl.bind(make_combo((_G["kbRestoreLock"] or "")), hl.dsp.exec_cmd("caelestia shell -d"), {locked = true})
hl.bind(make_combo((_G["kbRestoreLock"] or "")), hl.dsp.global("caelestia:lock"), {locked = true})
hl.bind(make_combo(", XF86MonBrightnessUp"), hl.dsp.global("caelestia:brightnessUp"), {locked = true})
hl.bind(make_combo(", XF86MonBrightnessDown"), hl.dsp.global("caelestia:brightnessDown"), {locked = true})
hl.bind(make_combo("Ctrl + Super, Space"), hl.dsp.global("caelestia:mediaToggle"), {locked = true})
hl.bind(make_combo(", XF86AudioPlay"), hl.dsp.global("caelestia:mediaToggle"), {locked = true})
hl.bind(make_combo(", XF86AudioPause"), hl.dsp.global("caelestia:mediaToggle"), {locked = true})
hl.bind(make_combo("Ctrl + Super, Equal"), hl.dsp.global("caelestia:mediaNext"), {locked = true})
hl.bind(make_combo(", XF86AudioNext"), hl.dsp.global("caelestia:mediaNext"), {locked = true})
hl.bind(make_combo("Ctrl + Super, Minus"), hl.dsp.global("caelestia:mediaPrev"), {locked = true})
hl.bind(make_combo(", XF86AudioPrev"), hl.dsp.global("caelestia:mediaPrev"), {locked = true})
hl.bind(make_combo(", XF86AudioStop"), hl.dsp.global("caelestia:mediaStop"), {locked = true})
hl.bind(make_combo("Ctrl + Super + Shift, R"), hl.dsp.exec_cmd("shell-restart --kill"), {release = true})
hl.bind(make_combo("Ctrl + Super + Alt, R"), hl.dsp.exec_cmd("shell-restart"), {release = true})
_G["wsaction"] = "~/.config/hypr/scripts/wsaction.fish"
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 1"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 1"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 2"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 2"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 3"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 3"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 4"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 4"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 5"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 5"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 6"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 6"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 7"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 7"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 8"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 8"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 9"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 9"))
hl.bind(make_combo((_G["kbGoToWs"] or "") .. ", 0"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " workspace 10"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 1"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 1"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 2"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 2"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 3"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 3"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 4"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 4"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 5"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 5"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 6"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 6"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 7"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 7"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 8"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 8"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 9"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 9"))
hl.bind(make_combo((_G["kbGoToWsGroup"] or "") .. ", 0"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g workspace 10"))
hl.bind(make_combo("Super, mouse_down"), hl.dsp.focus({ workspace = "-1" }))
hl.bind(make_combo("Super, mouse_up"), hl.dsp.focus({ workspace = "+1" }))
hl.bind(make_combo((_G["kbPrevWs"] or "")), hl.dsp.focus({ workspace = "-1" }), {repeating = true})
hl.bind(make_combo((_G["kbNextWs"] or "")), hl.dsp.focus({ workspace = "+1" }), {repeating = true})
hl.bind(make_combo("Super, Page_Up"), hl.dsp.focus({ workspace = "-1" }), {repeating = true})
hl.bind(make_combo("Super, Page_Down"), hl.dsp.focus({ workspace = "+1" }), {repeating = true})
hl.bind(make_combo("Ctrl + Super, mouse_down"), hl.dsp.focus({ workspace = "-10" }))
hl.bind(make_combo("Ctrl + Super, mouse_up"), hl.dsp.focus({ workspace = "+10" }))
hl.bind(make_combo((_G["kbToggleSpecialWs"] or "")), hl.dsp.exec_cmd("caelestia toggle specialws"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 1"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 1"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 2"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 2"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 3"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 3"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 4"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 4"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 5"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 5"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 6"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 6"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 7"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 7"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 8"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 8"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 9"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 9"))
hl.bind(make_combo((_G["kbMoveWinToWs"] or "") .. ", 0"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " movetoworkspace 10"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 1"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 1"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 2"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 2"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 3"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 3"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 4"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 4"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 5"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 5"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 6"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 6"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 7"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 7"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 8"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 8"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 9"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 9"))
hl.bind(make_combo((_G["kbMoveWinToWsGroup"] or "") .. ", 0"), hl.dsp.exec_cmd((_G["wsaction"] or "") .. " -g movetoworkspace 10"))
hl.bind(make_combo("Super + Alt, Page_Up"), hl.dsp.window.move({ workspace = "-1" }), {repeating = true})
hl.bind(make_combo("Super + Alt, Page_Down"), hl.dsp.window.move({ workspace = "+1" }), {repeating = true})
hl.bind(make_combo("Super + Alt, mouse_down"), hl.dsp.window.move({ workspace = "-1" }))
hl.bind(make_combo("Super + Alt, mouse_up"), hl.dsp.window.move({ workspace = "+1" }))
hl.bind(make_combo("Ctrl + Super + Shift, right"), hl.dsp.window.move({ workspace = "+1" }), {repeating = true})
hl.bind(make_combo("Ctrl + Super + Shift, left"), hl.dsp.window.move({ workspace = "-1" }), {repeating = true})
hl.bind(make_combo("Ctrl + Super + Shift, up"), hl.dsp.window.move({ workspace = "special:special" }))
hl.bind(make_combo("Ctrl + Super + Shift, down"), hl.dsp.window.move({ workspace = "e+0" }))
hl.bind(make_combo("Super + Alt, S"), hl.dsp.window.move({ workspace = "special:special" }))
hl.bind(make_combo((_G["kbWindowGroupCycleNext"] or "")), hl.dsp.window.cycle_next(), {repeating = true})
hl.bind(make_combo((_G["kbWindowGroupCyclePrev"] or "")), hl.dsp.window.cycle_next(), {repeating = true})
hl.bind(make_combo("Ctrl + Alt, Tab"), hl.dsp.group.next(), {repeating = true})
hl.bind(make_combo("Ctrl + Shift + Alt, Tab"), hl.dsp.group.prev(), {repeating = true})
hl.bind(make_combo((_G["kbToggleGroup"] or "")), hl.dsp.group.toggle())
hl.bind(make_combo((_G["kbUngroup"] or "")), hl.dsp.window.move({ out_of_group = true }))
hl.bind(make_combo("Super + Shift, Comma"), hl.dsp.group.lock_active())
hl.bind(make_combo("Super, left"), hl.dsp.focus({ direction = "l" }))
hl.bind(make_combo("Super, right"), hl.dsp.focus({ direction = "r" }))
hl.bind(make_combo("Super, up"), hl.dsp.focus({ direction = "u" }))
hl.bind(make_combo("Super, down"), hl.dsp.focus({ direction = "d" }))
hl.bind(make_combo("Super + Shift, left"), hl.dsp.window.move({ direction = "l" }))
hl.bind(make_combo("Super + Shift, right"), hl.dsp.window.move({ direction = "r" }))
hl.bind(make_combo("Super + Shift, up"), hl.dsp.window.move({ direction = "u" }))
hl.bind(make_combo("Super + Shift, down"), hl.dsp.window.move({ direction = "d" }))
hl.bind(make_combo("Super, mouse:272"), hl.dsp.window.drag(), {mouse = true})
hl.bind(make_combo((_G["kbMoveWindow"] or "")), hl.dsp.window.drag(), {mouse = true})
hl.bind(make_combo("Super, mouse:273"), hl.dsp.window.resize(), {mouse = true})
hl.bind(make_combo((_G["kbResizeWindow"] or "")), hl.dsp.window.resize(), {mouse = true})
hl.bind(make_combo("Ctrl + Super, Backslash"), hl.dsp.window.center())
hl.bind(make_combo("Ctrl + Super + Alt, Backslash"), hl.dsp.window.resize({ x = 800, y = 600, relative = false }))
hl.bind(make_combo("Ctrl + Super + Alt, Backslash"), hl.dsp.window.center())
hl.bind(make_combo((_G["kbWindowPip"] or "")), hl.dsp.exec_cmd("caelestia resizer pip"))
hl.bind(make_combo((_G["kbPinWindow"] or "")), hl.dsp.window.pin())
hl.bind(make_combo((_G["kbWindowFullscreen"] or "")), hl.dsp.window.fullscreen({ mode = ("0" == "0" and "fullscreen" or "maximized"), action = "toggle" }))
hl.bind(make_combo((_G["kbWindowBorderedFullscreen"] or "")), hl.dsp.window.fullscreen({ mode = ("1" == "0" and "fullscreen" or "maximized"), action = "toggle" }))
hl.bind(make_combo((_G["kbToggleWindowFloating"] or "")), hl.dsp.window.float({ action = "toggle" }))
hl.bind(make_combo((_G["kbCloseWindow"] or "")), hl.dsp.window.close())
hl.bind(make_combo((_G["kbSystemMonitor"] or "")), hl.dsp.exec_cmd("caelestia toggle sysmon"))
hl.bind(make_combo((_G["kbMusic"] or "")), hl.dsp.exec_cmd("caelestia toggle music"))
hl.bind(make_combo((_G["kbCommunication"] or "")), hl.dsp.exec_cmd("caelestia toggle communication"))
hl.bind(make_combo((_G["kbTodo"] or "")), hl.dsp.exec_cmd("caelestia toggle todo"))
hl.bind(make_combo("SUPER, Return"), hl.dsp.exec_cmd("ghostty"))
hl.bind(make_combo((_G["kbBrowser"] or "")), hl.dsp.exec_cmd("app2unit -- " .. (_G["browser"] or "")))
hl.bind(make_combo((_G["kbEditor"] or "")), hl.dsp.exec_cmd("app2unit -- " .. (_G["editor"] or "")))
hl.bind(make_combo("Super, G"), hl.dsp.exec_cmd("app2unit -- github-desktop"))
hl.bind(make_combo((_G["kbFileExplorer"] or "")), hl.dsp.exec_cmd("app2unit -- " .. (_G["fileExplorer"] or "")))
hl.bind(make_combo("Super + Alt, E"), hl.dsp.exec_cmd("app2unit -- nemo"))
hl.bind(make_combo("Ctrl + Alt, Escape"), hl.dsp.exec_cmd("app2unit -- qps"))
hl.bind(make_combo("Ctrl + Alt, V"), hl.dsp.exec_cmd("app2unit -- pavucontrol"))
hl.bind(make_combo(", Print"), hl.dsp.exec_cmd("caelestia screenshot"), {locked = true})
hl.bind(make_combo("Super + Shift, S"), hl.dsp.global("caelestia:screenshotFreeze"))
hl.bind(make_combo("Super + Shift + Alt, S"), hl.dsp.global("caelestia:screenshot"))
hl.bind(make_combo("Super + Alt, R"), hl.dsp.exec_cmd("caelestia record -s"))
hl.bind(make_combo("Ctrl + Alt, R"), hl.dsp.exec_cmd("caelestia record"))
hl.bind(make_combo("Super + Shift + Alt, R"), hl.dsp.exec_cmd("caelestia record -r"))
hl.bind(make_combo("Super + Shift, C"), hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind(make_combo(", XF86AudioMicMute"), hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), {locked = true})
hl.bind(make_combo(", XF86AudioMute"), hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), {locked = true})
hl.bind(make_combo("Super + Shift, M"), hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind(make_combo(", XF86AudioRaiseVolume"), hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ " .. (_G["volumeStep"] or "") .. "%+"), {locked = true, repeating = true})
hl.bind(make_combo(", XF86AudioLowerVolume"), hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ " .. (_G["volumeStep"] or "") .. "%-"), {locked = true, repeating = true})
hl.bind(make_combo("Super + Shift, L"), hl.dsp.exec_cmd("systemctl suspend-then-hibernate"))
hl.bind(make_combo("Super, V"), hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard"))
hl.bind(make_combo("Super + Alt, V"), hl.dsp.exec_cmd("pkill fuzzel || caelestia clipboard -d"))
hl.bind(make_combo("Super, Period"), hl.dsp.exec_cmd("pkill fuzzel || caelestia emoji -p"))
hl.bind(make_combo("Ctrl + Shift + Alt, V"), hl.dsp.exec_cmd("sleep 0.5s && ydotool type -d 1 \"$(cliphist list | head -1 | cliphist decode)\""), {locked = true})
hl.bind(make_combo("Super + Alt, f12"), hl.dsp.exec_cmd("notify-send -u low -i dialog-information-symbolic 'Test notification' \"Here's a really long message to test truncation and wrapping\nYou can middle click or flick this notification to dismiss it!\" -a 'Shell' -A \"Test1=I got it!\" -A \"Test2=Another action\""), {locked = true})