# ==========================================
# HYPRLAND CORE DEFINITIONS
# ==========================================

# --- APPS ---
$terminal = ghostty
$browser = zen-browser
$editor = kiro
$fileExplorer = nautilus

# --- HARDWARE DEFAULTS ---
$touchpadDisableTyping = true
$touchpadScrollFactor = 1.0
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# --- MISC ---
$volumeStep = 10
$cursorTheme = Bibata-Modern-Ice
$cursorSize = 24

# --- VISUALS ---
$workspaceGaps = 10
$windowGapsIn = 5
$windowGapsOut = 10
$singleWindowGapsOut = 10
$windowOpacity = 1.0
$windowRounding = 10
$windowBorderSize = 0

# ==========================================
# KEYBIND DEFINITIONS (The "Grammar")
# ==========================================

# Modifier Keys
$mainMod = Super
$shiftMod = Super+Shift
$ctrlMod = Super+Ctrl
$altMod = Super+Alt

# App Binds
$kbTerminal = $mainMod, Return
$kbBrowser = $mainMod, B
$kbEditor = $mainMod, C
$kbFileExplorer = $mainMod, E

# Workspace Binds
$kbGoToWs = $mainMod
$kbGoToWsGroup = Ctrl+Super
$kbMoveWinToWs = $shiftMod
$kbMoveWinToWsGroup = Ctrl+Super+Shift
$kbNextWs = $mainMod, Tab
$kbPrevWs = $shiftMod, Tab

# Window Actions
$kbCloseWindow = $mainMod, Q
$kbWindowFullscreen = $mainMod, F
$kbWindowBorderedFullscreen = $altMod, F
$kbToggleWindowFloating = $altMod, Space
$kbPinWindow = $mainMod, P
$kbMoveWindow = $mainMod, Z
$kbResizeWindow = $mainMod, X
$kbWindowPip = $altMod, Backslash

# Window Groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbToggleGroup = $mainMod, Comma
$kbUngroup = $mainMod, U

# Special Workspaces
$kbMusic = $mainMod, M
$kbCommunication = $mainMod, D
$kbTodo = $mainMod, R
$kbSystemMonitor = Ctrl+Shift, Escape
$kbToggleSpecialWs = $mainMod, S

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = $mainMod, K
$kbLock = $mainMod, L
$kbRestoreLock = $altMod, L
