hl.on("hyprland.start", function() hl.exec_cmd("gnome-keyring-daemon --start --components=secrets") end)
hl.on("hyprland.start", function() hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1") end)
hl.on("hyprland.start", function() hl.exec_cmd("wl-paste --type text --watch cliphist store") end)
hl.on("hyprland.start", function() hl.exec_cmd("wl-paste --type image --watch cliphist store") end)
hl.on("hyprland.start", function() hl.exec_cmd("trash-empty 30") end)
hl.on("hyprland.start", function() hl.exec_cmd("hyprctl setcursor sweet-cursors 24") end)
hl.on("hyprland.start", function() hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'sweet-cursors'") end)
hl.on("hyprland.start", function() hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 24") end)
hl.on("hyprland.start", function() hl.exec_cmd("/usr/lib/geoclue-2.0/demos/agent") end)
hl.on("hyprland.start", function() hl.exec_cmd("gammastep") end)
hl.on("hyprland.start", function() hl.exec_cmd("mpris-proxy") end)
hl.on("hyprland.start", function() hl.exec_cmd("caelestia resizer -d") end)
hl.on("hyprland.start", function() hl.exec_cmd("caelestia shell -d") end)
hl.on("hyprland.start", function() hl.exec_cmd("python3 ~/dotfiles/scripts/update_css_vars.py") end)
hl.on("hyprland.start", function() hl.exec_cmd("~/.config/caelestia/update_kdeglobals.sh") end)
hl.on("hyprland.start", function() hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland") end)
hl.on("hyprland.start", function() hl.exec_cmd("sleep 1 && /usr/lib/xdg-desktop-portal") end)