hl.window_rule({ match = { class = "^(com.mitchellh.ghostty)$" }, opacity = (_G["windowOpacity"] or "") .. " " .. (_G["windowOpacity"] or "") .. " override" })
hl.window_rule({ match = { class = "^(vesktop)$" }, opacity = (_G["windowOpacity"] or "") .. " " .. (_G["windowOpacity"] or "") .. " override" })
hl.window_rule({ match = { class = "^(com.mitchellh.ghostty)$" }, no_blur = false })
hl.window_rule({ match = { class = "^(vesktop)$" }, no_blur = false })
hl.window_rule({ match = { class = "^(obsidian)$" }, no_blur = false })
hl.window_rule({ match = { class = "^(caelestia-messenger)$" }, no_blur = false })
hl.window_rule({ match = { class = "^(obsidian)$" }, opacity = "0.99 0.99" })
hl.window_rule({ match = { class = "^(caelestia-messenger)$" }, opacity = "0.99 0.99" })
hl.window_rule({ match = { class = "foot|equibop|imv|swappy" }, opaque = true })
hl.window_rule({ match = { float = "true", xwayland = "false" }, center = true })
hl.window_rule({ match = { class = "guifetch" }, float = true })
hl.window_rule({ match = { class = "yad" }, float = true })
hl.window_rule({ match = { class = "zenity" }, float = true })
hl.window_rule({ match = { class = "wev" }, float = true })
hl.window_rule({ match = { class = "org\\.gnome\\.FileRoller" }, float = true })
hl.window_rule({ match = { class = "file-roller" }, float = true })
hl.window_rule({ match = { class = "blueman-manager" }, float = true })
hl.window_rule({ match = { class = "com\\.github\\.GradienceTeam\\.Gradience" }, float = true })
hl.window_rule({ match = { class = "feh" }, float = true })
hl.window_rule({ match = { class = "imv" }, float = true })
hl.window_rule({ match = { class = "system-config-printer" }, float = true })
hl.window_rule({ match = { class = "org\\.quickshell" }, float = true })
hl.window_rule({ match = { class = "foot", title = "nmtui" }, float = true })
hl.window_rule({ match = { class = "foot", title = "nmtui" }, size = "60% 70%" })
hl.window_rule({ match = { class = "foot", title = "nmtui" }, center = 1 })
hl.window_rule({ match = { class = "org\\.gnome\\.Settings" }, float = true })
hl.window_rule({ match = { class = "org\\.gnome\\.Settings" }, size = "70% 80%" })
hl.window_rule({ match = { class = "org\\.gnome\\.Settings" }, center = 1 })
hl.window_rule({ match = { class = "org\\.pulseaudio\\.pavucontrol|yad-icon-browser" }, float = true })
hl.window_rule({ match = { class = "org\\.pulseaudio\\.pavucontrol|yad-icon-browser" }, size = "60% 70%" })
hl.window_rule({ match = { class = "org\\.pulseaudio\\.pavucontrol|yad-icon-browser" }, center = 1 })
hl.window_rule({ match = { class = "nwg-look" }, float = true })
hl.window_rule({ match = { class = "nwg-look" }, size = "50% 60%" })
hl.window_rule({ match = { class = "nwg-look" }, center = 1 })
hl.window_rule({ match = { class = "btop" }, workspace = "special:sysmon" })
hl.window_rule({ match = { class = "discord|equibop|vesktop|whatsapp" }, workspace = "special:communication" })
hl.window_rule({ match = { class = "Todoist" }, workspace = "special:todo" })
hl.window_rule({ match = { title = "(Select|Open)( a)? (File|Folder)(s)?" }, float = true })
hl.window_rule({ match = { title = "File (Operation|Upload)( Progress)?" }, float = true })
hl.window_rule({ match = { title = ".* Properties" }, float = true })
hl.window_rule({ match = { title = "Export Image as PNG" }, float = true })
hl.window_rule({ match = { title = "GIMP Crash Debug" }, float = true })
hl.window_rule({ match = { title = "Save As" }, float = true })
hl.window_rule({ match = { title = "Library" }, float = true })
hl.window_rule({ match = { title = "Picture(-| )in(-| )[Pp]icture" }, move = "100%-w-2% 100%-w-3%" })
hl.window_rule({ match = { title = "Picture(-| )in(-| )[Pp]icture" }, keep_aspect_ratio = true })
hl.window_rule({ match = { title = "Picture(-| )in(-| )[Pp]icture" }, float = true })
hl.window_rule({ match = { title = "Picture(-| )in(-| )[Pp]icture" }, pin = true })
hl.window_rule({ match = { class = "steam" }, rounding = 10 })
hl.window_rule({ match = { title = "Friends List", class = "steam" }, float = true })
hl.window_rule({ match = { class = "steam_app_[0-9]+" }, immediate = true })
hl.window_rule({ match = { class = "steam_app_[0-9]+" }, idle_inhibit = "always" })
hl.window_rule({ match = { class = "com-atlauncher-App", title = "ATLauncher Console" }, float = true })
hl.window_rule({ match = { title = "Fusion360|(Marking Menu)", class = "fusion360\\.exe" }, no_blur = true })
hl.window_rule({ match = { xwayland = "1", title = "win[0-9]+" }, no_dim = true })
hl.window_rule({ match = { xwayland = "1", title = "win[0-9]+" }, no_shadow = true })
hl.window_rule({ match = { xwayland = "1", title = "win[0-9]+" }, rounding = 10 })
hl.workspace_rule({ workspace = "w[tv1]s[false]", gaps_out = (_G["singleWindowGapsOut"] or "") })
hl.workspace_rule({ workspace = "f[1]s[false]", gaps_out = (_G["singleWindowGapsOut"] or "") })
hl.layer_rule({ match = { namespace = "hyprpicker" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "logout_dialog" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "selection" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "wayfreeze" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "launcher" }, animation = "popin 80%" })
hl.layer_rule({ match = { namespace = "launcher" }, blur = true })
hl.layer_rule({ match = { namespace = "caelestia-(border-exclusion|area-picker)" }, no_anim = true })
hl.layer_rule({ match = { namespace = "caelestia-(drawers|background)" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "caelestia-drawers" }, blur = true })
hl.layer_rule({ match = { namespace = "caelestia-drawers" }, ignore_alpha = "0.57" })