# #######################################################################################
# WINDOW MODIFICATIONS (Blur, Opacity, Animations per app)
# #######################################################################################

# We removed individual opacity rules to keep all apps at constant 1.0 (sharp text).
# The background transparency is now handled natively by the apps or Zen mods.

# Animations
windowrule = animation slide, match:class ^(caelestia-launcher)$
windowrule = animation slide, match:class ^(caelestia-session)$
