# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Blur for waybar
#layerrule = blur, waybar
input {
	natural_scroll = false
}

bind = , PRINT, exec, grimblast copy area                                  # Take a screenshot

monitor = HDMI-A-1, 1440x900@59.88700, auto, 1
