background = #000000
foreground = #f9e0da
cursor-color = #f9b7a5
selection-background = #764638
selection-foreground = #ffdbd2
palette = 0=#000000
palette = 1=#ff9888
palette = 2=#ffd8be
palette = 3=#ffeee7
palette = 4=#ffa2bd
palette = 5=#ffa9ab
palette = 6=#ffdb94
palette = 7=#f9e0da
palette = 8=#30231f
palette = 9=#ff9888
palette = 10=#ffd8be
palette = 11=#ffeee7
palette = 12=#ffa2bd
palette = 13=#ffa9ab
palette = 14=#ffdb94
palette = 15=#f9e0da
palette = 16=#f9b7a5
palette = 17=#e7bdb2
palette = 18=#ffe1b1
