general {
    layout = dwindle
    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_workspaces = 10
    gaps_in = 5
    gaps_out = 10
    
    border_size = 0
}

decoration {
    rounding = 10

    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = true
        xray = false
        special = false
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = true
        input_methods = true
        size = 10
        passes = 2
        vibrancy = 0.1696
        vibrancy_darkness = 0.0
    }

    shadow {
        enabled = true
    }
}

render {
    direct_scanout = true
}

misc {
    vfr = true
    vrr = 1

    animate_manual_resizes = false
    animate_mouse_windowdragging = false

    disable_hyprland_logo = true
    force_default_wallpaper = 0

    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    middle_click_paste = false
    focus_on_activate = true
    session_lock_xray = true

    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

    background_color = 0xff$background
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = true
}